server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 50
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    url: http://localhost:5432
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jpa:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    oauth2:
#      client:
#        provider:
#          azure:
#            issuer-uri: https://login.microsoftonline.com/19ba435d-e46c-436a-84f2-1b01e693e480/oauth2/v2.0/
#        registration:
#          azure:
#
#            client-secret: GWi8Q~~Y8ZIHLmIbRl3lY9x5V4rUWLAReRhUCbzr
#            client-id: 98ae5342-0c4c-4587-b76d-0c873a78c438
#            scope:
#              - openid
#              - email
#              - profile

  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 19ba435d-e46c-436a-84f2-1b01e693e480
        credential:
          client-id: 98ae5342-0c4c-4587-b76d-0c873a78c438
          client-secret: GWi8Q~~Y8ZIHLmIbRl3lY9x5V4rUWLAReRhUCbzr
        redirect-uri-template: http://localhost:8080/login/oauth2/code/
        authorization-clients:
          graph:
            scopes: https://graph.microsoft.com/Analytics.Read, https://graph.microsoft.com/User.Read, email, profile, openid




logging:
  level:
    org.springframework.security: TRACE